# Site settings
title: Morijin
subtitle: V.Portfolio
email: jiki.mori@gmail.com
description: HTML/CSS/WEBDESIGN/MARKUP/PORTFOLIO
baseurl:  # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 
city: SeongNamCity
state: 
zip_code: 10000
country: Korea
phone: (010) 6876-6333

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url:
github_url: http://morijin.github.io
gitlab_url: 
googleplus_url: 
instagram_url: https://instagram.com
linkedin_url: 
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown

sass:
  style: compressed
